version: "3"
services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: production
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    environment:
      - NODE_ENV=test
    command: npm run start
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-db-data:/data/db
      - mongo-db-config:/data/configdb

volumes:
  mongo-db-data:
  mongo-db-config:
